React Pages Migration: Conditions
Coursemology/coursemology2 pull request #5154
Opened 2022-09-28 06:16 UTC by purfectliterature

Part of #5098. Closes #3570.

2022-10-04 05:59 UTC, purfectliterature commented
Remaining specs to resolve:
`spec/features/course/assessment_condition_management_spec.rb`
`spec/features/course/achievement_condition_management_spec.rb`

2022-10-05 08:04 UTC, ekowidianto requested changes
Great work as always! Some comments below:
- [x] Is _assessment_condition.html.slim still used anywhere else?
- [x] It feels a bit misleading to put the `ConditionsManager` folder inside `form/fields`. Do you think it would be better to put it under `lib/coponents/course/condition` or somewhere else? What do you think?
- [ ] When retrieving conditions (achievement, assessment and survey), you should only retrieve the available ones (eg see achievements/_form/html.slim line 3, and the same for assessment and survey). This will prevent the obvious illegal condition to be set in the first place. Also, instead of re-using the index APIs for achievement, assessment and survey, you can create new API endpoints to retrieve these conditions (via each specific condition controller - we can call it `def available_achievements` for example). This way, we dont need to retrieve all unnecessary information via the index endpoint which will slow down the query process since we only need the `id` and `title` anyway. (bonus: you dont need to filter out its own condition in the frontend anymore).
- [ ] Sort the list of achievement, assessment and survey by the name.
- [ ] Using 1010s data, I get some key error warnings for achievement condition.
- [ ] When there is an error after a condition deletion, there is no error message and it fails silently. 
- [ ] For create/update, if the error returned is not of validation error (eg network error, 403/404, error etc), add a toast error message. Otherwise, it would fail silently. Also `errors.errors` may be undefined, as such we need to check for it before calling `setError`

2022-10-07 15:19 UTC, purfectliterature commented on client/app/lib/components/form/fields/ConditionsManager/conditions/AnyCondition.ts
> +import { ConditionData } from 'types/course/conditions';
I only put types that represent our app's business logic, e.g., models, backend conformers, etc. In this case, `AnyCondition` is a 'generic' interface that `*Condition.tsx`s in the future should use, i.e., it is just a component's (props) supporting interface.

Declaring these types in `conditions/index.tsx` will cause a dependency cycle:
- `*Condition.tsx`s import `AnyCondition` from `conditions/index.tsx`, and
- `specifiers.ts` imports `*Condition.tsx` and `AnyCondition` from `conditions/index.tsx`,

hence resulting in dependency cycles in `*Condition.tsx`s via `specifiers.ts`.

Due to these reasons, I made a separate `AnyCondition.ts` in `conditions`.

2022-10-07 15:41 UTC, purfectliterature commented
To continue from #5115:
- [ ] Consolidate `Prompt` and `ConditionDialog`
- [ ] Deprecate `ConfirmationDialog`
- [ ] Convert all `useEffect`/`isLoading` to `Preload` for instant fetch error catching
- [ ] Implement global `Form` `disable` for UI freezing
- [ ] `Form` heads-up to freeze or use `LoadingButton`
- [ ] Convert all boolean states to `useToggle`

2022-10-10 15:55 UTC, purfectliterature commented on client/app/lib/components/form/fields/ConditionsManager/index.tsx
> +          <Button
Sure, but I was not really sure why we need to disable it. 

When the menu is open, it is in a separate presentation overlay, so clicking anywhere outside the menu will first dismiss the menu, hence double-clicking the button is impossible. And if for whatever reason it becomes possible, `toggleAdding` will just set `adding` to `false` and the menu will disappear (as expected).

2022-10-10 15:56 UTC, purfectliterature commented on client/app/lib/components/form/fields/ConditionsManager/conditions/ConditionDialog.tsx
> +export default ConditionDialog;
`ConditionDialog` is now removed. `*Condition` now uses `Prompt`, and `Prompt` itself now supports more advanced customisations.

2022-10-14 03:11 UTC, ekowidianto approved these changes
Thanks for the changes!

2022-10-14 03:19 UTC, merged