Display Statistics Table on Assessment Overview on Course Statistics
Coursemology/coursemology2 pull request #7187
Opened 2024-03-15 07:38 UTC by bivanalhar

## Feature

We implemented the Assessments Statistics Table, which displays the overview of each assessments within a course, and practically how students inside the course perform generally inside that course. We provide the following information, for each assessment:

- Under which Tab and Category the assessment belongs to
- Statistics regarding the number of students who submitted successfully, submitted late, and still attempting
- The average and standard deviation for both students' grades and also time taken for them to finish the assessment

## Overview

<img width="1528" alt="Screenshot 2024-03-15 at 3 38 16 PM" src="https://github.com/Coursemology/coursemology2/assets/16359075/3970f195-bff4-4e60-a491-f4d8ef5dc1ec">

2024-08-06 06:02 UTC, bivanalhar commented on app/controllers/concerns/course/statistics/reference_times_concern.rb
> +
oh this is just for the sake of readability only..

2024-08-07 03:37 UTC, bivanalhar commented on client/app/lib/helpers/url-helpers.js
> +
done

2024-08-07 03:37 UTC, bivanalhar commented on client/app/bundles/course/statistics/pages/StatisticsIndex/index.tsx
> +  const [tabValue, setTabValue] = useState(defaultTabIndex);
done

2024-08-07 03:38 UTC, bivanalhar commented on app/controllers/concerns/course/statistics/counts_concern.rb
> +    @personal_end_at_hash = personal_end_at_hash(@assessments.pluck(:id), current_course.id)
done.. now each of the function runs around 2-4s for the course with personal times

2024-09-05 19:57 UTC, cysjonathan requested changes
1. Add a column "Starts at" and default ordering should be based on "Starts at" first, then "Title" if there is a tie.
2. Center the # Attempted/Submitted/Late and make the numbers clickable, pointing to the /submissions page.
3. Avg Grade / Total Grade, Total Grade should be a whole number, remove the 2 d.p.
4. Avg Grade can limit to 1 d.p., ideally truncate to whole number if it is x.0
5. Avg Time / Stdev Time ideally should truncate to largest significant value (e.g. 42 days or 2 days or 17 hours or 3 minutes)

2024-09-06 04:55 UTC, bivanalhar commented
> 1. Add a column "Starts at" and default ordering should be based on "Starts at" first, then "Title" if there is a tie.
done

> 2. Center the # Attempted/Submitted/Late and make the numbers clickable, pointing to the /submissions page.
done

> 3. Avg Grade / Total Grade, Total Grade should be a whole number, remove the 2 d.p.
Sometimes the grades can be not a whole number, in this case the decimal points are set to either 0 or 1

> 4. Avg Grade can limit to 1 d.p., ideally truncate to whole number if it is x.0
done

> 5. Avg Time / Stdev Time ideally should truncate to largest significant value (e.g. 42 days or 2 days or 17 hours or 3 minutes)
not doing it right now

2024-09-12 06:07 UTC, cysjonathan approved these changes

2024-09-12 06:08 UTC, merged